### ISSUE TITLE
又来求救了

### ISSUE THREAD

**Issue by liffzaici** [yzyyz1387/nonebot_plugin_workscore#3]
![image](https://user-images.githubusercontent.com/98678215/151942766-ab742d6e-8015-4c82-93ea-993af33e3b7d.png)

这是完整报错，我的是nonebot2确认，有啥不对的请老哥见谅。

**Comment by yzyyz1387** [comment]
烦请弄明白nb2 alpha和beta的区别，日后将适配beta
